fix potential exception in ExpressionFactory initialization (not sure if this is the root cause of tests failing since r7099 with a `NoClassDefFoundError`)
git-svn-id: http://josm.openstreetmap.de/svn/trunk@7103 0c6e7542-c601-0410-84e7-c038aed88b3b